# Generated by Django 3.1.9 on 2021-05-05 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('AL', 'Alapuzha'), ('ER', 'Ernakulam'), ('ID', 'Iduki'), ('KN', 'Kannur'), ('KL', 'Kollam'), ('KS', 'Kasargod'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malapuram'), ('PL', 'Palakkad'), ('PT', 'Pathanamthitta'), ('TV', 'Thiruvanathapuram'), ('TS', 'Thrissur'), ('WA', 'Wayanad')], max_length=2)),
                ('phone', models.CharField(max_length=15)),
                ('sector', models.CharField(choices=[('gov', 'government'), ('prv', 'private')], max_length=3)),
                ('covid_beds', models.IntegerField()),
                ('normal_beds', models.IntegerField()),
                ('icu_beds', models.IntegerField()),
                ('ventilator', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('adharno', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('district', models.CharField(choices=[('AL', 'Alapuzha'), ('ER', 'Ernakulam'), ('ID', 'Iduki'), ('KN', 'Kannur'), ('KL', 'Kollam'), ('KS', 'Kasargod'), ('KT', 'Kottayam'), ('KZ', 'Kozhikode'), ('MA', 'Malapuram'), ('PL', 'Palakkad'), ('PT', 'Pathanamthitta'), ('TV', 'Thiruvanathapuram'), ('TS', 'Thrissur'), ('WA', 'Wayanad')], max_length=2)),
                ('category', models.CharField(choices=[('cv', 'Covid'), ('NC', 'Non-covid')], max_length=2)),
                ('states', models.CharField(choices=[('W', 'Waiting'), ('A', 'Admitted'), ('D', 'Discharged')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('C', 'Covid'), ('N', 'Normal'), ('I', 'Icu'), ('V', 'Ventilator')], max_length=2)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.patient')),
            ],
        ),
    ]
