# Generated by Django 3.1.9 on 2021-05-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='states',
            new_name='status',
        ),
    ]
