# Generated by Django 3.2 on 2021-05-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0003_auto_20210508_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
    ]
