# Generated by Django 3.2 on 2021-05-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0005_hospital_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
    ]
